"""initial_schema

Revision ID: 65d003844d47
Revises: 
Create Date: 2026-09-11 21:01:50.420097

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '65d003844d47'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('providers',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('provider_type', sa.String(length=50), nullable=False),
    sa.Column('website_url', sa.String(length=1000), nullable=True),
    sa.Column('country', sa.String(length=3), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('providers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_providers_name'), ['name'], unique=False)

    op.create_table('student_profiles',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('citizenship_country', sa.String(length=3), nullable=False),
    sa.Column('residence_country', sa.String(length=3), nullable=False),
    sa.Column('intended_degree_level', sa.String(length=50), nullable=False),
    sa.Column('intended_destination_country', sa.String(length=3), nullable=False),
    sa.Column('gpa', sa.Float(), nullable=True),
    sa.Column('gpa_scale', sa.Float(), nullable=True),
    sa.Column('intended_major', sa.String(length=255), nullable=True),
    sa.Column('english_test_type', sa.String(length=50), nullable=True),
    sa.Column('english_test_score', sa.Float(), nullable=True),
    sa.Column('sat_score', sa.Integer(), nullable=True),
    sa.Column('act_score', sa.Integer(), nullable=True),
    sa.Column('financial_need_tier', sa.String(length=50), nullable=True),
    sa.Column('academic_achievements', sa.JSON(), nullable=False),
    sa.Column('extracurricular_activities', sa.JSON(), nullable=False),
    sa.Column('interests', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('student_profiles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_student_profiles_citizenship_country'), ['citizenship_country'], unique=False)

    op.create_table('universities',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('state', sa.String(length=50), nullable=False),
    sa.Column('country', sa.String(length=3), nullable=False),
    sa.Column('admissions_need_policy', sa.String(length=50), nullable=False),
    sa.Column('official_admissions_url', sa.String(length=1000), nullable=True),
    sa.Column('official_financial_aid_url', sa.String(length=1000), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('universities', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_universities_name'), ['name'], unique=True)

    op.create_table('scholarship_opportunities',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('provider_id', sa.String(length=36), nullable=True),
    sa.Column('university_id', sa.String(length=36), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('target_degree_level', sa.String(length=50), nullable=False),
    sa.Column('destination_country', sa.String(length=3), nullable=False),
    sa.Column('academic_cycle', sa.String(length=20), nullable=False),
    sa.Column('varies_by_program', sa.Boolean(), nullable=False),
    sa.Column('international_students_allowed', sa.String(length=20), nullable=False),
    sa.Column('requires_sat', sa.String(length=20), nullable=False),
    sa.Column('requires_act', sa.String(length=20), nullable=False),
    sa.Column('requires_css_profile', sa.String(length=20), nullable=False),
    sa.Column('financial_need_required', sa.String(length=20), nullable=False),
    sa.Column('verification_status', sa.String(length=50), nullable=False),
    sa.Column('fingerprint_sha256', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['university_id'], ['universities.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('scholarship_opportunities', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_scholarship_opportunities_fingerprint_sha256'), ['fingerprint_sha256'], unique=True)
        batch_op.create_index(batch_op.f('ix_scholarship_opportunities_provider_id'), ['provider_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_scholarship_opportunities_slug'), ['slug'], unique=True)
        batch_op.create_index(batch_op.f('ix_scholarship_opportunities_title'), ['title'], unique=False)
        batch_op.create_index(batch_op.f('ix_scholarship_opportunities_university_id'), ['university_id'], unique=False)

    op.create_table('application_requirements',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('scholarship_id', sa.String(length=36), nullable=False),
    sa.Column('requirement_type', sa.String(length=50), nullable=False),
    sa.Column('kind', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('instructions', sa.Text(), nullable=True),
    sa.Column('submission_format', sa.String(length=100), nullable=True),
    sa.Column('source_evidence_snippet', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['scholarship_id'], ['scholarship_opportunities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('application_requirements', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_application_requirements_scholarship_id'), ['scholarship_id'], unique=False)

    op.create_table('awards',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('scholarship_id', sa.String(length=36), nullable=False),
    sa.Column('funding_classification', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('is_renewable', sa.String(length=20), nullable=False),
    sa.Column('renewal_criteria', sa.Text(), nullable=True),
    sa.Column('estimated_annual_value_usd', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['scholarship_id'], ['scholarship_opportunities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('awards', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_awards_scholarship_id'), ['scholarship_id'], unique=True)

    op.create_table('conflict_records',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('scholarship_id', sa.String(length=36), nullable=False),
    sa.Column('field_name', sa.String(length=100), nullable=False),
    sa.Column('source_a_value', sa.Text(), nullable=False),
    sa.Column('source_a_url', sa.String(length=1000), nullable=False),
    sa.Column('source_b_value', sa.Text(), nullable=False),
    sa.Column('source_b_url', sa.String(length=1000), nullable=False),
    sa.Column('resolution_status', sa.String(length=50), nullable=False),
    sa.Column('resolution_notes', sa.Text(), nullable=True),
    sa.Column('recorded_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['scholarship_id'], ['scholarship_opportunities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('conflict_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_conflict_records_scholarship_id'), ['scholarship_id'], unique=False)

    op.create_table('deadlines',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('scholarship_id', sa.String(length=36), nullable=False),
    sa.Column('deadline_type', sa.String(length=50), nullable=False),
    sa.Column('deadline_date', sa.Date(), nullable=True),
    sa.Column('is_exact_date', sa.Boolean(), nullable=False),
    sa.Column('timezone', sa.String(length=50), nullable=True),
    sa.Column('academic_cycle', sa.String(length=20), nullable=False),
    sa.Column('varies_by_program', sa.Boolean(), nullable=False),
    sa.Column('context_description', sa.Text(), nullable=True),
    sa.Column('source_evidence_snippet', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['scholarship_id'], ['scholarship_opportunities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('deadlines', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_deadlines_scholarship_id'), ['scholarship_id'], unique=False)

    op.create_table('discovery_sources',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('scholarship_id', sa.String(length=36), nullable=False),
    sa.Column('url', sa.String(length=1000), nullable=False),
    sa.Column('source_name', sa.String(length=255), nullable=False),
    sa.Column('authority_tier', sa.String(length=50), nullable=False),
    sa.Column('discovery_notes', sa.Text(), nullable=True),
    sa.Column('discovered_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['scholarship_id'], ['scholarship_opportunities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('discovery_sources', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_discovery_sources_scholarship_id'), ['scholarship_id'], unique=False)

    op.create_table('eligibility_rules',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('scholarship_id', sa.String(length=36), nullable=False),
    sa.Column('rule_id', sa.String(length=100), nullable=False),
    sa.Column('kind', sa.String(length=50), nullable=False),
    sa.Column('expression_json', sa.JSON(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('source_evidence_snippet', sa.Text(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['scholarship_id'], ['scholarship_opportunities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('eligibility_rules', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_eligibility_rules_scholarship_id'), ['scholarship_id'], unique=False)

    op.create_table('official_sources',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('scholarship_id', sa.String(length=36), nullable=False),
    sa.Column('url', sa.String(length=1000), nullable=False),
    sa.Column('source_domain', sa.String(length=255), nullable=False),
    sa.Column('authority_tier', sa.String(length=50), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('page_title', sa.String(length=500), nullable=True),
    sa.Column('extracted_text_snippet', sa.Text(), nullable=True),
    sa.Column('last_crawled_at', sa.DateTime(), nullable=True),
    sa.Column('last_http_status', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['scholarship_id'], ['scholarship_opportunities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('official_sources', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_official_sources_scholarship_id'), ['scholarship_id'], unique=False)

    op.create_table('requirements',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('scholarship_id', sa.String(length=36), nullable=False),
    sa.Column('requirement_type', sa.String(length=50), nullable=False),
    sa.Column('kind', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('source_evidence_snippet', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['scholarship_id'], ['scholarship_opportunities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('requirements', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_requirements_scholarship_id'), ['scholarship_id'], unique=False)

    op.create_table('verification_records',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('scholarship_id', sa.String(length=36), nullable=False),
    sa.Column('verification_state', sa.String(length=50), nullable=False),
    sa.Column('verifier_identity', sa.String(length=100), nullable=False),
    sa.Column('verification_method', sa.String(length=100), nullable=False),
    sa.Column('evidence_url', sa.String(length=1000), nullable=False),
    sa.Column('evidence_quote', sa.Text(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('verified_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['scholarship_id'], ['scholarship_opportunities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('verification_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_verification_records_scholarship_id'), ['scholarship_id'], unique=False)

    op.create_table('funding_components',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('award_id', sa.String(length=36), nullable=False),
    sa.Column('component_type', sa.String(length=50), nullable=False),
    sa.Column('amount_min', sa.Float(), nullable=True),
    sa.Column('amount_max', sa.Float(), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('amount_period', sa.String(length=30), nullable=False),
    sa.Column('percentage_tuition', sa.Float(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('source_evidence_snippet', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['award_id'], ['awards.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('funding_components', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_funding_components_award_id'), ['award_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('funding_components', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_funding_components_award_id'))

    op.drop_table('funding_components')
    with op.batch_alter_table('verification_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_verification_records_scholarship_id'))

    op.drop_table('verification_records')
    with op.batch_alter_table('requirements', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_requirements_scholarship_id'))

    op.drop_table('requirements')
    with op.batch_alter_table('official_sources', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_official_sources_scholarship_id'))

    op.drop_table('official_sources')
    with op.batch_alter_table('eligibility_rules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_eligibility_rules_scholarship_id'))

    op.drop_table('eligibility_rules')
    with op.batch_alter_table('discovery_sources', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_discovery_sources_scholarship_id'))

    op.drop_table('discovery_sources')
    with op.batch_alter_table('deadlines', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_deadlines_scholarship_id'))

    op.drop_table('deadlines')
    with op.batch_alter_table('conflict_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_conflict_records_scholarship_id'))

    op.drop_table('conflict_records')
    with op.batch_alter_table('awards', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_awards_scholarship_id'))

    op.drop_table('awards')
    with op.batch_alter_table('application_requirements', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_application_requirements_scholarship_id'))

    op.drop_table('application_requirements')
    with op.batch_alter_table('scholarship_opportunities', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_scholarship_opportunities_university_id'))
        batch_op.drop_index(batch_op.f('ix_scholarship_opportunities_title'))
        batch_op.drop_index(batch_op.f('ix_scholarship_opportunities_slug'))
        batch_op.drop_index(batch_op.f('ix_scholarship_opportunities_provider_id'))
        batch_op.drop_index(batch_op.f('ix_scholarship_opportunities_fingerprint_sha256'))

    op.drop_table('scholarship_opportunities')
    with op.batch_alter_table('universities', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_universities_name'))

    op.drop_table('universities')
    with op.batch_alter_table('student_profiles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_student_profiles_citizenship_country'))

    op.drop_table('student_profiles')
    with op.batch_alter_table('providers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_providers_name'))

    op.drop_table('providers')
    # ### end Alembic commands ###
